--
-- Tables
-- This file declares all tables in the public schema.
--

-- Extensions
create extension if not exists "http" with schema "extensions";
create extension if not exists "citext" with schema "extensions";

-- Private schema (used by sales policies migration)
create schema if not exists "private";

create table public.companies (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sector text,
    size smallint,
    linkedin_url text,
    website extensions.citext,
    phone_number text,
    address text,
    zipcode text,
    city text,
    state_abbr text,
    sales_id bigint,
    context_links json,
    country text,
    description text,
    revenue text,
    tax_identifier text,
    logo jsonb,
    nb_sites integer
);

create table public.contacts (
    id bigint generated by default as identity primary key,
    first_name text,
    last_name text,
    gender text,
    title text,
    background text,
    avatar jsonb,
    first_seen timestamp with time zone,
    last_seen timestamp with time zone,
    has_newsletter boolean,
    status text,
    tags bigint[],
    company_id bigint,
    sales_id bigint,
    linkedin_url text,
    email_jsonb jsonb,
    phone_jsonb jsonb,
    company_start_date date,
    decision_role text,
    relationship_status text,
    linked_contact_ids bigint[]
);

create table public.contact_notes (
    id bigint generated by default as identity (sequence name public."contactNotes_id_seq") not null,
    contact_id bigint not null,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    status text,
    attachments jsonb[]
);

create table public.deals (
    id bigint generated by default as identity primary key,
    name text not null,
    company_id bigint,
    contact_ids bigint[],
    category text,
    stage text not null,
    description text,
    amount bigint,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    archived_at timestamp with time zone,
    expected_closing_date date,
    sales_id bigint,
    index smallint,
    confidentiality text,
    reference text,
    origin text,
    motivation text,
    objectives text[],
    other_expectations text
);

create table public.deal_notes (
    id bigint generated by default as identity (sequence name public."dealNotes_id_seq") not null,
    deal_id bigint not null,
    type text,
    text text,
    date timestamp with time zone default now(),
    sales_id bigint,
    attachments jsonb[]
);

create table public.sales (
    id bigint generated by default as identity primary key,
    first_name text not null default 'Pending'::text,
    last_name text not null default 'Pending'::text,
    email extensions.citext not null,
    administrator boolean not null,
    user_id uuid not null,
    avatar jsonb,
    disabled boolean not null default false
);

create unique index uq__sales__user_id on public.sales using btree (user_id);

create table public.tags (
    id bigint generated by default as identity primary key,
    name text not null,
    color text not null
);

create table public.tasks (
    id bigint generated by default as identity primary key,
    contact_id bigint not null,
    type text,
    text text,
    due_date timestamp with time zone,
    done_date timestamp with time zone,
    sales_id bigint,
    location text,
    mode text
);

-- User-extensible option lists (deal origins, deal objectives, meeting modes
-- and meeting types). Rows are the available labels; records store the label
-- itself, so a deleted choice never orphans existing data.
create table public.choices (
    id bigint generated by default as identity primary key,
    category text not null,
    label text not null
);

create unique index uq__choices__category_label on public.choices using btree (category, label);

-- Discovery record ("etat des lieux") following the VitalO IMPACT 360 method.
-- Columns are grouped by the section of the paper form they come from.
create table public.assessments (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    company_id bigint not null,
    -- Diagnose / governance & engagement
    governance_maturity text,
    governance_owners text[],
    governance_owners_other text,
    governance_forums text[],
    governance_forums_other text,
    -- Diagnose / existing programs
    existing_programs text[],
    existing_programs_comments text,
    -- Diagnose / managerial maturity
    manager_training text[],
    manager_confidence text,
    -- Diagnose / priority issues
    priority_issues text[],
    priority_issues_other text,
    priority_issues_comments text,
    -- Diagnose / company strengths
    company_strengths text[],
    company_strengths_other text,
    company_strengths_comments text,
    -- Diagnose / identified barriers
    identified_barriers text[],
    identified_barriers_other text,
    identified_barriers_comments text,
    -- Diagnose / urgency
    urgency_level text,
    urgency_comments text,
    -- Diagnose / top three priorities expressed by the client
    client_priority_1 text,
    client_priority_2 text,
    client_priority_3 text,
    -- Diagnose / IMPACT 360 profile, one level per dimension (1 to 4)
    impact_awareness smallint,
    impact_management smallint,
    impact_prevention smallint,
    impact_steering smallint,
    impact_culture smallint,
    impact_measurement smallint,
    overall_profile_level smallint,
    overall_profile_comments text,
    -- Recommend / diagnostic summary
    diagnostic_summary text,
    -- Recommend / priority support objectives
    support_objectives text[],
    support_objectives_other text,
    -- Recommend / steps of the recommended IMPACT 360 journey
    journey_steps text[],
    recommended_path text[],
    -- Recommend / consultant recommendations
    consultant_recommendations text[],
    consultant_recommendations_other text,
    -- Recommend / audiences covered
    target_audiences text[],
    target_audience_other text,
    -- Recommend / deployment priority, by time horizon
    deployment_short_term text[],
    deployment_medium_term text[],
    deployment_long_term text[],
    -- Recommend / expected benefits, success factors and watch points
    expected_benefits text,
    success_factors text[],
    success_factors_other text,
    watch_points text,
    -- Concretize / interview summary
    interview_summary text,
    -- Concretize / project deciders, one name and influence level per role
    decider_management_name text,
    decider_management_influence text,
    decider_hr_name text,
    decider_hr_influence text,
    decider_manager_name text,
    decider_manager_influence text,
    decider_cse_name text,
    decider_cse_influence text,
    decider_other_name text,
    decider_other_influence text,
    -- Concretize / decision process
    decision_process text[],
    decision_process_other text,
    expected_decision_date date,
    -- Concretize / budget
    budget_status text,
    estimated_budget numeric,
    -- Concretize / next steps, as [{ action, owner_id, due_date }]
    next_steps jsonb,
    -- Concretize / documents to send
    documents_to_send text[],
    documents_to_send_other text,
    -- Concretize / next follow-up
    next_follow_up_date date,
    next_follow_up_mode text,
    -- Concretize / opportunity rating, from 1 to 5 stars
    opportunity_rating smallint,
    opportunity_rating_comments text,
    -- Concretize / file follow-up
    follow_up_status text[],
    follow_up_comments text,
    -- Concretize / development potential
    development_opportunities text[],
    development_opportunities_other text,
    development_comments text,
    -- Concretize / checklist and closing
    closing_checklist text[],
    closed_by_id bigint,
    closed_at date,
    next_action text
);

create table public.configuration (
    id integer not null default 1 primary key,
    config jsonb not null default '{}'::jsonb,
    constraint configuration_singleton check (id = 1)
);

create table public.favicons_excluded_domains (
    id bigint generated by default as identity primary key,
    domain text not null
);

--
-- Foreign keys
--

alter table public.assessments
    add constraint assessments_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.assessments
    add constraint assessments_closed_by_id_fkey foreign key (closed_by_id) references public.sales(id);

alter table public.companies
    add constraint companies_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contacts
    add constraint contacts_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.contacts
    add constraint contacts_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.contact_notes
    add constraint "contactNotes_contact_id_fkey" foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

alter table public.contact_notes
    add constraint "contactNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_company_id_fkey foreign key (company_id) references public.companies(id) on update cascade on delete cascade;

alter table public.deals
    add constraint deals_sales_id_fkey foreign key (sales_id) references public.sales(id);

alter table public.deal_notes
    add constraint "dealNotes_deal_id_fkey" foreign key (deal_id) references public.deals(id) on update cascade on delete cascade;

alter table public.deal_notes
    add constraint "dealNotes_sales_id_fkey" foreign key (sales_id) references public.sales(id);

alter table public.sales
    add constraint sales_user_id_fkey foreign key (user_id) references auth.users(id);

alter table public.tasks
    add constraint tasks_contact_id_fkey foreign key (contact_id) references public.contacts(id) on update cascade on delete cascade;

-- Legacy primary key constraint names (from before snake_case rename)
alter table only public.contact_notes
    add constraint "contactNotes_pkey" primary key (id);

alter table only public.deal_notes
    add constraint "dealNotes_pkey" primary key (id);

--
-- Indexes on foreign keys
--

create index assessments_company_id_idx on public.assessments using btree (company_id);
create index contact_notes_contact_id_idx on public.contact_notes using btree (contact_id);
create index contacts_company_id_idx on public.contacts using btree (company_id);
create index deal_notes_deal_id_idx on public.deal_notes using btree (deal_id);
create index deals_company_id_idx on public.deals using btree (company_id);
