
  create table "public"."sales_documents" (
    "id" bigint generated by default as identity not null,
    "sales_id" bigint not null,
    "type" text not null,
    "file" jsonb not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."sales_documents" enable row level security;

alter table "public"."choices" add column "requires_renewal" boolean not null default false;

CREATE UNIQUE INDEX sales_documents_pkey ON public.sales_documents USING btree (id);

CREATE UNIQUE INDEX uq__sales_documents__sales_id_type ON public.sales_documents USING btree (sales_id, type);

alter table "public"."sales_documents" add constraint "sales_documents_pkey" PRIMARY KEY using index "sales_documents_pkey";

alter table "public"."sales_documents" add constraint "sales_documents_sales_id_fkey" FOREIGN KEY (sales_id) REFERENCES public.sales(id) ON DELETE CASCADE not valid;

alter table "public"."sales_documents" validate constraint "sales_documents_sales_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.is_own_sale(sale_id bigint)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  return exists (
    select 1 from public.sales where id = sale_id and user_id = auth.uid()
  );
end;
$function$
;

grant delete on table "public"."sales_documents" to "anon";

grant insert on table "public"."sales_documents" to "anon";

grant references on table "public"."sales_documents" to "anon";

grant select on table "public"."sales_documents" to "anon";

grant trigger on table "public"."sales_documents" to "anon";

grant truncate on table "public"."sales_documents" to "anon";

grant update on table "public"."sales_documents" to "anon";

grant delete on table "public"."sales_documents" to "authenticated";

grant insert on table "public"."sales_documents" to "authenticated";

grant references on table "public"."sales_documents" to "authenticated";

grant select on table "public"."sales_documents" to "authenticated";

grant trigger on table "public"."sales_documents" to "authenticated";

grant truncate on table "public"."sales_documents" to "authenticated";

grant update on table "public"."sales_documents" to "authenticated";

grant delete on table "public"."sales_documents" to "service_role";

grant insert on table "public"."sales_documents" to "service_role";

grant references on table "public"."sales_documents" to "service_role";

grant select on table "public"."sales_documents" to "service_role";

grant trigger on table "public"."sales_documents" to "service_role";

grant truncate on table "public"."sales_documents" to "service_role";

grant update on table "public"."sales_documents" to "service_role";


  create policy "Enable delete for owner"
  on "public"."sales_documents"
  as permissive
  for delete
  to authenticated
using (public.is_own_sale(sales_id));



  create policy "Enable insert for owner"
  on "public"."sales_documents"
  as permissive
  for insert
  to authenticated
with check (public.is_own_sale(sales_id));



  create policy "Enable read for owner and admins"
  on "public"."sales_documents"
  as permissive
  for select
  to authenticated
using ((public.is_own_sale(sales_id) OR public.is_admin()));



  create policy "Enable update for owner"
  on "public"."sales_documents"
  as permissive
  for update
  to authenticated
using (public.is_own_sale(sales_id))
with check (public.is_own_sale(sales_id));




-- Default administrative papers expected from every consultant. The list is
-- editable from the settings page, so these are a starting point, not a fixed
-- set. `requires_renewal` marks the ones that expire one year after filing.
insert into public.choices (category, label, requires_renewal) values
    ('user_document_type', 'Carte d''identité', false),
    ('user_document_type', 'RIB', false),
    ('user_document_type', 'Attestation de vigilance URSSAF', true),
    ('user_document_type', 'Attestation d''assurance responsabilité civile professionnelle', true)
on conflict (category, label) do nothing;
